@endpoint = http://localhost:5156/api/Language

### SELECT ALL
GET {{endpoint}}

### SELECT BY ID
GET {{endpoint}}/6

### CREATE
POST {{endpoint}}
Content-Type: application/json; charset=UTF-8

{
    "name" : "restClientExtension Test"
}

### UPDATE
PUT {{endpoint}}/40
Content-Type: application/json; charset=UTF-8

{
    "name" : "update Test"
}

### DELETE
DELETE {{endpoint}}/40

